### PR TITLE
Added solutions for c6-2 - c6-5

### PR DESCRIPTION
**Pull request by rimfire41**
Added solutions for challenges c6-2, c6-3, c6-4 and c6-5.

c6-5 may fail to function due to a game bug where assassins jump out of bounds.

### CODE REVIEW

**Comment by Yoshi128986** [comment]
I can't be bothered to export it somewhere where i can copy it on my phone, but for c6-4 i would like it to be switched to 
Attack speed
Impetus
Fire impetus
Multishot
Basic Bouncing
Incineration
Chained Ball
Volcano Gift
Fire Attack
Magma foundation
Add a note that wave streaming should be on, but nothing else that can take accel above 5 the reason for this change is because your current one is bugged and a non bugged version would likely not work

**Comment by rimfire41** [comment]
> I can't be bothered to export it somewhere where i can copy it on my phone, but for c6-4 i would like it to be switched to Attack speed Impetus Fire impetus Multishot Basic Bouncing Incineration Chained Ball Volcano Gift Fire Attack Magma foundation Add a note that wave streaming should be on, but nothing else that can take accel above 5 the reason for this change is because your current one is bugged and a non bugged version would likely not work

Made the changes. See if you'd like the software requirements to be described in another way. You should be able to edit the pull request if you're a maintainer

**Comment by Yoshi128986** [comment]
I'm not going to overwrite what you do, but suggestion for c6-5, replace Phasing, which i think does nothing, with Heartstopper aura, for those assassins who decide to leave, this may help

**Comment by rimfire41** [comment]
> I'm not going to overwrite what you do, but suggestion for c6-5, replace Phasing, which i think does nothing, with Heartstopper aura, for those assassins who decide to leave, this may help

Yeah phasing kinda does nothing. I was going to say it's pointless to add heartstopper aura as assassins can still fall way outside aura range, but the added kill speed for every other enemy like air and earth, alone makes it worth it

**Pull request merged**
